name: Makefile CI

on:
  workflow_dispatch:
    branches: [ master ]
  #pull_request:
  #  branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
     
    #- name: Install dependencies
    #  run: make
      
    - name: Run check
      run: make check
      
    - name: Run distcheck
      run: make build-test
    
    - name: Make tcl-filter.tapp
      run: cd pandoc-tcl-filter && make tcl-filter.tapp
    - uses: actions/upload-artifact@v2
      with:
        name: pandoc-tcl-filter.tapp upload
        path: pandoc-tcl-filter/pandoc-tcl-filter.tapp
