name: Makefile CI

on:
  workflow_dispatch:
    branches: [ master ]
  #pull_request:
  #  branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
     
    #- name: Install dependencies
    #  run: make
      
    - name: Run check
      run: make check
      
    - name: Run distcheck
      run: make build-test
    
    - name: Make pandoc-tcl-filter.tapp
      run: make pandoc-bin
