name: Makefile CI

on:
  workflow_dispatch:
    branches: [ master ]
  #pull_request:
  #  branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
     
    #- name: Install dependencies
    #  run: make
      
    - name: Run check
      run: make check
      
    - name: Run distcheck
      run: make build-test
    
    - name: Make pandoc-tcl-filter.tapp
      run: make pandoc-bin
  deploy:
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - name: Release result
              uses: marvinpinto/action-automatic-releases@v1.2.1
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: "latest"
                  prerelease: true
                  title: "Development Build"
                  files: |
                    pandoc-tcl-filter.tapp
